# Generated by Django 5.2.8 on 2025-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicFareLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=30)),
                ("old_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("changed_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "DynamicFareLog",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RevenueAnalysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("flight_date", models.DateField()),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_seats", models.IntegerField()),
                ("sold_seats", models.IntegerField()),
            ],
            options={
                "db_table": "RevenueAnalysis",
                "managed": False,
            },
        ),
    ]
