# Generated by Django 5.2.8 on 2025-11-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone_num", models.CharField(blank=True, max_length=20, null=True)),
                ("user_type", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Member",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="members.member",
                    ),
                ),
                ("role", models.IntegerField()),
            ],
            options={
                "db_table": "Admin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="members.member",
                    ),
                ),
                ("mileage", models.IntegerField(default=0)),
                ("grade", models.CharField(default="Bronze", max_length=20)),
            ],
            options={
                "db_table": "Customer",
                "managed": False,
            },
        ),
    ]
