# Generated by Django 5.2.8 on 2025-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("method", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("paid_at", models.DateTimeField()),
            ],
            options={
                "db_table": "Payment",
                "managed": False,
            },
        ),
    ]
