# Generated by Django 5.2.8 on 2025-11-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "aircraft_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("model", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
            ],
            options={
                "db_table": "Aircraft",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "airport_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("airport_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Airport",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("flight_id", models.AutoField(primary_key=True, serialize=False)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Flight",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_no", models.CharField(max_length=10)),
                ("seat_class", models.CharField(max_length=20)),
                ("status", models.CharField(default="AVAILABLE", max_length=20)),
            ],
            options={
                "db_table": "Seat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                ("base_duration", models.DurationField()),
                (
                    "destination",
                    models.ForeignKey(
                        db_column="destination",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="flights.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        db_column="origin",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="flights.airport",
                    ),
                ),
            ],
            options={
                "db_table": "Route",
            },
        ),
    ]
