# Generated by Django 5.2.8 on 2025-11-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"managed": False},
        ),
    ]
