# Generated by Django 5.2.8 on 2025-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("seat_no", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("reserved_at", models.DateTimeField()),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "Reservation",
                "managed": False,
            },
        ),
    ]
